spring.application.name=Reservation_TABack

server.port=8002
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
allowed.origins=http://localhost:5173

#Keycloak Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KC_ISSUER_HOST}/realms/${KC_REALM_NAME}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KC_HOST}/realms/${KC_REALM_NAME}/protocol/openid-connect/certs

logging.level.org.keycloak=DEBUG

jwt.auth.converter.principle-attribute=preferred-username
jwt.auth.converter.resource-id=spring-client-api-rest

# Descuentos
discount.group.min-passengers=4
discount.group.percent=10
discount.frequent.min-reservations=3
discount.frequent.percent=10
discount.multi-package.percent=5
discount.max-total-percent=20